Fix #2 Change japanize initalization
uehara1414/japanize-matplotlib pull request #9
Opened 2020-02-12 12:29 UTC by vaaaaanquish

# 変更箇所

 - https://github.com/uehara1414/japanize-matplotlib/issues/2 への対応
 - ttfファイルへのpath、fontsへのpathの取得をメソッド化
 - setup.py, Pipfileを更新

### https://github.com/uehara1414/japanize-matplotlib/issues/2 への対応

import時ではなくjapanizeメソッドを実行した際にフォントが有効化されるようにしました。
```
import matplotlib.pyplot as plt
import japanize_matplotlib
japanize_matplotlib.japanize()
```
また、この変更で破壊的変更となるためメジャーバージョンを更新しています。

### fontへのpathの取得をメソッド化

matplotlibのwrapperや周辺モジュールを利用する際、japanize_matplotlibのフォントが利用できるよう、フォントファイル等のpathの取得をメソッド化しました。

例として、以下のようなWordCloudモジュール等が挙げられます。
```
import matplotlib.pyplot as plt
import japanize_matplotlib
from wordcloud import WordCloud

wordcloud = WordCloud(font_path=str(japanize_matplotlib.get_font_ttf_path()))
words = {'テスト':0.5, 'demo':0.2, '算出':0.1, '531':0.1}
wordcloud.fit_words(words)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.imshow(wordcloud)
```

### setup.py, Pipfileを更新

Pipfile必要なパッケージを整理。setup.pyの以下の項目を追加しています。
- long_description (pypi上でMarkdownが表示されるようになります)
- licenseをsetup.pyにも追記しています (pypi上で表示されるようになります
- install_requiresとしてmatplotlibを指定しています

2020-02-12 13:51 UTC, uehara1414 commented
@vaaaaanquish 対応ありがとうございます！
2点修正したい点があります。

## 1. #2 への対応について
> import時ではなくjapanizeメソッドを実行した際にフォントが有効化されるようにしました。

japanizeメソッドを実行した際**も**フォント有効化されるようにしたいです。

#2 にてその旨を書いておらず後出しという形になってしまいますが、import するだけで日本語化が完了するのは本モジュールのコアコンセプトであり、機能として無くしたくはないです。
import に副作用があるのが気持ち悪いと感じるかもしれませんが、ご理解ください。

## 2. fontへのpathの取得をメソッド化について
取得できるpathを文字列型にしたいです。

こちらも後出しになってしまって申し訳ないですが、実は将来的に pathlib への依存は外そうと思っています。
外した時に外部のAPIの仕様がかわる（Path型からstr型になる）のを避けたいです。

pahtlibはPython3.4から実装されたモジュールです。このモジュールに依存しているということは、3.4以前のバージョンのPythonにて本モジュールが利用できない状況になっているということです。
本モジュールは細かいことを気にせず幅広く利用してもらいたく作成したものなので、「ちょっと昔のプロジェクトに導入したらなぜか動かない、なんでだ？」と困惑する状況を生み出したくないです。

2020-02-12 14:21 UTC, vaaaaanquish commented
> japanizeメソッドを実行した際もフォント有効化されるようにしたいです。  

良いと思います。https://github.com/uehara1414/japanize-matplotlib/pull/9/commits/5af4de126ab14ddded8407baf42b873dc1ef2ebc にて対応しました。
 

> こちらも後出しになってしまって申し訳ないですが、実は将来的に pathlib への依存は外そうと思っています。

良いと思います。https://github.com/uehara1414/japanize-matplotlib/pull/9/commits/100440adc4302c125fdd561dcea49c757e564a90 にて対応しました。

demo.pyの動作を確認、os.pathを利用するよう改修し、以下の動作についても確認しました。
```
type(japanize_matplotlib.get_font_path())  # str
type(japanize_matplotlib.get_font_ttf_path())  # str
```

2020-02-13 11:49 UTC, uehara1414 commented
@vaaaaanquish 対応ありがとうございます！
週末にゆっくり動作確認や細かいレビューなど行おうと思います、少々お待ちを

2020-04-04 10:58 UTC, vaaaaanquish commented
@uehara1414 レビューは進んでいますか？

2020-04-11 08:41 UTC, uehara1414 commented
@vaaaaanquish 今日やります。待たせてしまってすみません

2020-04-11 13:18 UTC, uehara1414 requested changes
@vaaaaanquish 
動作は大丈夫でした。細かいところになりますが、バージョン番号だけ修正していただきたいです。よろしくお願いします。

2020-04-11 13:18 UTC, uehara1414 commented on setup.py
> +      version='2.0.0',
後方互換性の保たれた形の修正にしていただいたので、合わせてバージョンもメジャーアップデートからマイナーバージョンアップデートの 1.1.0 へ修正お願いします。

2020-04-11 16:26 UTC, vaaaaanquish commented on setup.py
> +      version='2.0.0',
@uehara1414 レビューありがとうございます。対応しました。

2020-04-27 18:52 UTC, vaaaaanquish commented on setup.py
> +      version='2.0.0',
@uehara1414 こちらいかがでしょうか？

2020-05-03 06:47 UTC, uehara1414 commented on setup.py
> +      version='2.0.0',
@vaaaaanquish 大丈夫でした、マージしますね

2020-05-03 06:48 UTC, merged